# Generated by Django 5.2.4 on 2025-10-23 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('defectuoso', 'Defectuoso'), ('contingencia', 'Contingencia'), ('reparacion', 'En Reparacion'), ('funcional', 'Funcional'), ('nuevo', 'Nuevo')], default='funcional', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('recepcion', 'Recepcion'), ('custodio', 'Custodio'), ('revision', 'Revision'), ('clonacion', 'Clonacion'), ('masterizacion', 'Masterizacion'), ('entregado', 'Entregado'), ('kit', 'Kit')], default='recepcion', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('laptop', 'Laptop'), ('cpu', 'CPU'), ('monitor', 'Monitor'), ('impresora', 'Impresora'), ('mouse', 'Mouse'), ('teclado', 'Teclado'), ('audifonos', 'Audifonos'), ('otros', 'Otros')], default='cpu', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.estado')),
                ('kit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seguimiento.kit')),
                ('tipo_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.tipoequipo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ArmadoKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.equipo')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.kit')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.estado')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.fase')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.kit')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.equipo')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.estado')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.fase')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.usuario')),
            ],
        ),
    ]
