# Generated by Django 5.2.4 on 2025-10-24 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Llave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_equipo', models.CharField(max_length=100, unique=True)),
                ('contador_cambio', models.IntegerField(default=0)),
                ('contador_nuevo_registro', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='contrasena',
            new_name='rol',
        ),
        migrations.RemoveField(
            model_name='armadokit',
            name='description',
        ),
        migrations.RemoveField(
            model_name='fase',
            name='description',
        ),
        migrations.RemoveField(
            model_name='fase',
            name='observations',
        ),
        migrations.RemoveField(
            model_name='kit',
            name='description',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='description',
        ),
        migrations.AddField(
            model_name='armadokit',
            name='codigo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientokit',
            name='fue_asignado_a_operador',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fase',
            name='nombre',
            field=models.CharField(choices=[('recepcion', 'Recepcion'), ('custodio', 'Custodio'), ('revision', 'Revision'), ('clonacion', 'Clonacion'), ('masterizacion', 'Masterizacion'), ('entregado_a_ope', 'Entregado'), ('en_kit', 'Kit'), ('no_recibido', 'No Recibido')], default='no_recibido', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='llave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seguimiento.llave'),
        ),
        migrations.AddField(
            model_name='movimientokit',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seguimiento.operador'),
        ),
        migrations.CreateModel(
            name='RegistroDesplieguegue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.CharField(max_length=100)),
                ('fue_desplegado', models.BooleanField(default=False)),
                ('llego_destino', models.BooleanField(default=False)),
                ('incidentes', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.operador')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_estacion', models.CharField(max_length=100)),
                ('registro_inicial', models.IntegerField(default=0)),
                ('registro_final', models.IntegerField(default=0)),
                ('contaddor_cambios_inicial', models.IntegerField(default=0)),
                ('contador_cambios_final', models.IntegerField(default=0)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('incidentes', models.TextField(blank=True, null=True)),
                ('llave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.llave')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.operador')),
            ],
        ),
    ]
