# Generated by Django 5.2.4 on 2025-10-24 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0002_llave_operador_rename_contrasena_usuario_rol_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistroKeys',
            new_name='RegistroKey',
        ),
        migrations.CreateModel(
            name='RegistroDespliegue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.CharField(max_length=100)),
                ('fue_desplegado', models.BooleanField(default=False)),
                ('llego_destino', models.BooleanField(default=False)),
                ('incidentes', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.operador')),
            ],
        ),
        migrations.DeleteModel(
            name='RegistroDesplieguegue',
        ),
    ]
