# Generated by Django 5.2.4 on 2025-10-27 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0003_rename_registrokeys_registrokey_registrodespliegue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('ruta', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tipoequipo',
            name='observations',
        ),
        migrations.AddField(
            model_name='operador',
            name='correo',
            field=models.EmailField(default=0.04, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operador',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='operador',
            name='estado',
            field=models.CharField(blank=True, choices=[('postulante', 'Postulante'), ('seleccionado', 'Seleccionado'), ('contratado', 'Contratado'), ('sin_firmar_contrato', 'Sin Firmar Contrato'), ('renuncia', 'Renuncia')], default='postulante', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='operador',
            name='coordinador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seguimiento.coordinador'),
        ),
    ]
